### PR TITLE
Fixes #36

### LINKED ISSUE #36: Allow to configure all MySQL settings
Hi Jordan,

I'm creating this issue with a PR to allow end user to configure all aspects of the MySQL connection:

**DATABASE_NAME**: `MySQL database name`
**DATABASE_USER**: `MySQL database username`
**DATABASE_PASSWORD**: `MySQL user password`
**DATABASE_HOST**: `MySQL server hostname`
**DATABASE_PORT**: `MySQL server port`

This is useful when running MySQL on remote containers/servers (My case) and specially when not using default 3306 port.

Hope this helps someone else.

Thanks!

### PR DESCRIPTION
**Pull request by amontalban**
Fixes #36

### CODE REVIEW

**Comment by jjethwa** [comment]
Thanks so much @amontalban 

More configuration options is always a good thing :)

**Comment by jjethwa** [comment]
Hi @amontalban 

I need to revert this merge.  I should have reviewed it a bit more.  Looks like it's causing an issue for users with local MySQL instances Probably one of the seds needs to be updated

**Comment by amontalban** [comment]
Hi @jjethwa 

Sorry to hear that, I'm going to give it a more deep test and let you know.

Thanks!

**Comment by jjethwa** [comment]
@amontalban 

No problem at all and thanks :)

**Comment by amontalban** [comment]
Hi @jjethwa 

Do you have more info about the issue you said above? Because seems to be working for me.

I'm thinking that maybe the issue was with the changed parameters, say RUNDECK_PASSWORD with DATABASE_PASSSWORD?

Thanks!

**Comment by jjethwa** [comment]
@amontalban 

Unfortunately, I had to revert your other PRs too to get us back to the previous state cleanly without having to edit things manually.  Sorry for the extra work :(

For this PR, I think we'll need to keep support for the old env vars like RUNDECK_PASSWORD, but add a note in the readme and an echo in the run script to let users know that the old variables are deprecated so they know to move to the new ones you've added.  I made a bad choice with the naming conventions when I started, your convention is a lot easier for new users to understand without looking at the readme.

I haven't had a chance to look into what the issue was, but for users using the local MySQL DB, the had this exception:

java.sql.SQLException: Access denied for user 'rundeck'@'localhost' (using password: YES)

So maybe an issue with the rundeck user not having it's password updated in MySQL or the password not getting updated in the properties file?

**Comment by jjethwa** [comment]
Hi @amontalban 

I'm back from vacation :)  There was another PR to reduce the layers and it's been merged already to dev and master.   If you have time, are you interested in looking into your 3 PRs again? :)

**Comment by amontalban** [comment]
Hi @jjethwa,

Sure I will try to find some time to do it as we had to put this project aside in our env.

Will let you know once they are ready.

Thanks!

**Pull request merged**
