### PR TITLE
Update to rundeck 3.2.1

### PR DESCRIPTION
**Pull request by NiTRoeSE**
Update to rundeck version to 3.2.1

### CODE REVIEW

**Comment by jjethwa** [comment]
Thanks @NiTRoeSE 

Is there a reason for changing the spacing of the Dockerfile?  Also, the bintray and SHASUM for rd-cli should still be OK for this release.

**Comment by NiTRoeSE** [comment]
Ah i see... no there is no reason for spacing, its a copy failure, i update the pull request tomorrow.

**Comment by jjethwa** [comment]
Thanks so much 😄

**Comment by NiTRoeSE** [comment]
> Thanks so much 😄

No Problem.. :)  ... i rember why i changed cli- source from bintray to github .. github was just the first i found and i was in hurry... I must have looked the wrong way. :D .. however, i changed it back to bintray. 

regards

**Comment by jjethwa** [comment]
Awesome, thanks @NiTRoeSE 

Really appreciate it 😄

**Pull request merged**
