### PR TITLE
Ignore the presence of lost+found in a newly created FS

### PR DESCRIPTION
**Pull request by h4wkmoon**

### CODE REVIEW

**Comment by h4wkmoon** [comment]
Will fix #159

**Comment by jjethwa** [comment]
bump @h4wkmoon

**Comment by h4wkmoon** [comment]
patch-1 updated. MySQL suffers froù the same problem.
Is there anything I need to do regarding the PR ?

**Comment by jjethwa** [comment]
Thanks @h4wkmoon 

Sorry, I did not get notified of changes until you commented.  Really appreciate it! 😄

**Pull request merged**
