### PR TITLE
Upgrade Rundeck 3.4.1

### PR DESCRIPTION
**Pull request by sylvaindd**

### CODE REVIEW

**Comment by sylvaindd** [comment]
Also made a change to the server_uuid prop replacement in this PR.
I meant to do it in another PR but failed, tell me if you want me to revert and resubmit it.

**Comment by jjethwa** [comment]
Hi @sylvaindd 

Sorry for the delay, I'll be able to merge and test tomorrow my time.  The update for the UUID looks great!  Thanks so much! 😃

**Comment by jjethwa** [comment]
Hi @sylvaindd 

Really sorry, I'll get to this as soon as I can.  Got sick the other day and recovering slowly.

**Review by jjethwa — APPROVED** [review]

**Comment by jjethwa** [comment]
Thanks @sylvaindd 

Just merged and the container should be available in 30 - 60 minutes once testing is completed.  Really appreciate it 😄

**Pull request merged**
