### PR TITLE
allow to set rundeck database username

### PR DESCRIPTION
**Pull request by jfcoz**
When using external database, allow to set rundeck database username

### CODE REVIEW

**Review by jjethwa — APPROVED** [review]

**Comment by jjethwa** [comment]
Thanks @jfcoz 

Really appreciate the PR.  it's merged and should be available in latest within the next 30 minutes via Docker Hub 😄

**Comment by seboss666** [comment]
I've tried to deploy the update, letting the default values, but the rundeck refuses to connect to local database, even if credentials are correct. The error is pretty confusing to me. I've managed to cur down the horridous java stack trace to these messages :  
```
java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
(... 150+ lines of "at ..." indications...)
Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
```
To be honest I was using a rather old image for now (3.0.22). What have changed ?

**Comment by seboss666** [comment]
Nevermind, I found this, but it's not real documentation that mariadb stopped using TZ environment variable in the package used :/
https://github.com/jjethwa/rundeck/issues/177

**Comment by jjethwa** [comment]
Hi @seboss666 

So you're good using the referenced fix (setting the timezone in the MariaDB config)?

**Pull request merged**
