### PR TITLE
adds ability to enable cluster mode

### PR DESCRIPTION
**Pull request by andrewmeissner**
I thought the ability to enable cluster mode might be beneficial to some users, myself included.  :)

### CODE REVIEW

**Comment by andrewmeissner** [comment]
@jjethwa do you have any thoughts or input on this?  :)

**Comment by jjethwa** [comment]
Hi @andrewmeissner 

Sorry, I'll take a look and test as soon as I can.  On a short holiday at the moment :stuck_out_tongue:

**Comment by andrewmeissner** [comment]
No worries, @jjethwa !  Enjoy your time!  :)

**Comment by jjethwa** [comment]
Thanks @adamdecaf 

Just reviewed and merged!  Really appreciate it 😄

**Pull request merged**
